# Generated by Django 4.0.3 on 2022-06-05 22:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_social', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('adress', models.CharField(max_length=255, null=True)),
                ('years', models.DateField(null=True)),
                ('tel', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Le numéro de mobile saisi n'est pas au bon format !", regex='^[0-9]{10,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Logiciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
                ('duree_licence', models.CharField(max_length=255, null=True)),
                ('data_debut_licence', models.DateField(null=True)),
                ('data_fin_licence', models.DateField(null=True)),
                ('agence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPJ.agence')),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPJ.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Materiels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
                ('caracteristiques', models.CharField(max_length=255, null=True)),
                ('marque', models.CharField(max_length=255, null=True)),
                ('autre', models.CharField(blank=True, max_length=255, null=True)),
                ('data_acquisition', models.DateField(null=True)),
                ('garantie', models.CharField(blank=True, max_length=255, null=True)),
                ('agence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPJ.agence')),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPJ.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, null=True, unique=True)),
                ('prenom', models.CharField(blank=True, max_length=250)),
                ('date_nais', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Le numéro de mobile saisi n'est pas au bon format !", regex='^[0-9]{10,15}$')])),
                ('adress', models.CharField(max_length=255, null=True)),
                ('fonction', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Typelogiciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Typemateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_declaration_panne', models.DateTimeField(auto_now_add=True, null=True)),
                ('description_panne', models.TextField()),
                ('Etat_panne', models.CharField(choices=[('Encours', 'Encours'), ('En attente', 'En attente')], default='En attente', max_length=200, null=True)),
                ('agence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPJ.agence')),
                ('logiciel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPJ.logiciel')),
                ('materiel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPJ.materiels')),
                ('type_logiciel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPJ.typelogiciel')),
                ('type_materiel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPJ.typemateriel')),
            ],
        ),
        migrations.AddField(
            model_name='materiels',
            name='type_materiel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPJ.typemateriel'),
        ),
        migrations.AddField(
            model_name='logiciel',
            name='type_logiciel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPJ.typelogiciel'),
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_intervention', models.DateTimeField(auto_now_add=True, null=True)),
                ('observation', models.TextField()),
                ('solution', models.TextField()),
                ('cout_de_reparation', models.IntegerField()),
                ('Etat_intervention', models.BooleanField(default=True)),
                ('agence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPJ.agence')),
                ('materiel_en_panne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPJ.panne')),
                ('technicien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPJ.technicien')),
                ('type_logiciel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPJ.typelogiciel')),
                ('type_materiel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPJ.typemateriel')),
            ],
        ),
    ]
