# Generated by Django 4.0.3 on 2022-06-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPJ', '0002_remove_intervention_agence_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materiels',
            new_name='Materiel',
        ),
        migrations.AlterModelOptions(
            name='intervention',
            options={'ordering': ['-date_intervention']},
        ),
        migrations.AlterModelOptions(
            name='materiel',
            options={'ordering': ['-data_acquisition']},
        ),
        migrations.AlterModelOptions(
            name='panne',
            options={'ordering': ['-date_declaration_panne']},
        ),
        migrations.AlterField(
            model_name='panne',
            name='date_declaration_panne',
            field=models.DateTimeField(),
        ),
    ]
