# Generated by Django 4.0.3 on 2022-06-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPJ', '0003_rename_materiels_materiel_alter_intervention_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panne',
            name='date_declaration_panne',
            field=models.DateField(),
        ),
    ]
