# Generated by Django 4.0.3 on 2022-06-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPJ', '0004_alter_panne_date_declaration_panne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panne',
            name='Etat_panne',
            field=models.CharField(choices=[('Encours', 'Encours'), ('En attente', 'En attente')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='panne',
            name='date_declaration_panne',
            field=models.DateField(null=True),
        ),
    ]
