# Generated by Django 4.0.3 on 2022-06-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPJ', '0005_alter_panne_etat_panne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panne',
            name='date_declaration_panne',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
