# Generated by Django 4.0.3 on 2022-06-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPJ', '0006_alter_panne_date_declaration_panne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panne',
            name='date_declaration_panne',
            field=models.DateField(null=True),
        ),
    ]
