# Generated by Django 4.0.3 on 2022-06-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPJ', '0007_alter_panne_date_declaration_panne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervention',
            old_name='materiel_en_panne',
            new_name='panne_concerner',
        ),
    ]
