# Generated by Django 4.0.3 on 2022-07-18 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppPJ', '0008_rename_materiel_en_panne_intervention_panne_concerner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPJ.agence'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPJ.agence'),
        ),
        migrations.AddField(
            model_name='technicien',
            name='agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPJ.agence'),
        ),
    ]
