# Generated by Django 4.0.3 on 2022-07-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPJ', '0009_fournisseur_agence_intervention_agence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicien',
            name='tel',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
