# Generated by Django 4.0.3 on 2022-07-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPJ', '0011_remove_technicien_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicien',
            name='tel',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='tel',
            field=models.CharField(max_length=13),
        ),
    ]
