# Generated by Django 4.0.3 on 2022-07-19 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppPJ', '0012_technicien_tel_alter_fournisseur_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='panne',
            name='agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPJ.agence'),
        ),
        migrations.AlterField(
            model_name='panne',
            name='Etat_panne',
            field=models.CharField(choices=[('Terminer', 'Terminer'), ('En attente', 'En attente')], max_length=200, null=True),
        ),
    ]
